#pragma once

#include <filesystem>

#include "paths.h"

namespace fs = std::filesystem;

class App;
class Console;

class UserConfig
{
public:

    /// <summary>
    /// Unreal Engine project build config
    /// </summary>
    enum class BuildConfig : char
    {
        Development, 
        Shipping
    };
    /// <summary>
    /// Must follow the Unreal Engine naming for build configs, otherwise packaging will fail.
    /// </summary>
    const char* const BuildConfigs[2] =
    { 
        "Development", 
        "Shipping"
    };
    BuildConfig buildConfig = BuildConfig::Development;

    Paths paths;

    /// <summary>
    /// Should the config be saved and loaded automatically?
    /// </summary>
    bool autoLoadSave = true;

    /// <summary>
    /// Should all directories be detected automatically if possible?
    /// </summary>
    bool autoDetectAll = true;

    char target[128] = "MyGameEditor"; // default value
    char platform[128] = "Win64";        // default value
    char itchioChannel[128] = "windows";        // default value
    char usergame[512] = "";

    /// <summary>
    /// Is the config data defaulted or loaded from file?
    /// </summary>
    bool loaded = false;

    static float fontScale;

    UserConfig();
    void Save(App& app);
    void Load(App& app);

    /// <summary>
    /// Loads the json file and forwards it directly into a string, so it could be printed out in the console for example.
    /// </summary>
    /// <returns></returns>
    std::string LoadToString() const;

    /// <summary>
    /// Deletes all temporary files generated by the app, including imgui.ini and pipeline settings json file.
    /// </summary>
    /// <param name="console"></param>
    void DeleteTemporaryFiles(Console* console = nullptr);

    /// <summary>
    /// Takes a c-style string representing a path, if there is a trailing slash (at the end of the path), it removes it in-place.
    /// </summary>
    template <int N>
    static void RemoveTrailingSlash(char (&path)[N])
    {
        for (int i = 0; i < sizeof(path) / sizeof(path[0]); ++i)
        {
            if (path[i] == 0) // path end
            {
                if (i > 0)
                {
                    // remove trailing slash
                    if (path[i - 1] == '/' || path[i - 1] == '\\')
                    {
                        path[i - 1] = 0;
                    }
                }
                break;
            }
        }
    }

    /// <summary>
    /// Returns currently chosen build config as a string, valid for direct use in UAT. Prefer this function over manual conversion/indexing.
    /// </summary>
    /// <returns></returns>
    inline std::string GetCurrentBuildConfigString() const
    {
        return BuildConfigs[static_cast<size_t>(buildConfig)];
    }
};